/**
 * 48 cities, 8 per region. Real coordinates and local currencies.
 *
 * `costIndex` is a 1–100 scale where 50 is the global average for a mid-range
 * traveller. `avgStayCost` (USD per night) and `avgMealCost` (USD per day) are
 * what the budget engine uses as the starting point for a new stop, so they
 * have to be plausible rather than decorative.
 */

export type SeedCity = {
  slug: string;
  name: string;
  country: string;
  countryCode: string;
  region: string;
  lat: number;
  lng: number;
  costIndex: number;
  popularity: number;
  currency: string;
  timezone: string;
  description: string;
  avgStayCost: number;
  avgMealCost: number;
};

export const REGIONS = [
  "Europe",
  "Asia",
  "South Asia",
  "Americas",
  "Africa & Middle East",
  "Oceania",
] as const;

export const cities: SeedCity[] = [
  /* ---------------------------------------------------------------- Europe */
  {
    slug: "paris",
    name: "Paris",
    country: "France",
    countryCode: "FR",
    region: "Europe",
    lat: 48.8566,
    lng: 2.3522,
    costIndex: 78,
    popularity: 98,
    currency: "EUR",
    timezone: "Europe/Paris",
    description:
      "Nineteenth-century boulevards, riverside booksellers and a museum on nearly every corner. Walkable enough that the Métro is optional for most of a short trip.",
    avgStayCost: 165,
    avgMealCost: 55,
  },
  {
    slug: "rome",
    name: "Rome",
    country: "Italy",
    countryCode: "IT",
    region: "Europe",
    lat: 41.9028,
    lng: 12.4964,
    costIndex: 68,
    popularity: 95,
    currency: "EUR",
    timezone: "Europe/Rome",
    description:
      "Three thousand years of city stacked on itself, with ruins sitting casually between apartment blocks. Summer is punishing, so most visitors aim for spring or October.",
    avgStayCost: 130,
    avgMealCost: 45,
  },
  {
    slug: "barcelona",
    name: "Barcelona",
    country: "Spain",
    countryCode: "ES",
    region: "Europe",
    lat: 41.3874,
    lng: 2.1686,
    costIndex: 64,
    popularity: 93,
    currency: "EUR",
    timezone: "Europe/Madrid",
    description:
      "Modernista architecture on a grid plan, with a city beach fifteen minutes from the old town. Dinner rarely starts before nine.",
    avgStayCost: 120,
    avgMealCost: 42,
  },
  {
    slug: "amsterdam",
    name: "Amsterdam",
    country: "Netherlands",
    countryCode: "NL",
    region: "Europe",
    lat: 52.3676,
    lng: 4.9041,
    costIndex: 76,
    popularity: 88,
    currency: "EUR",
    timezone: "Europe/Amsterdam",
    description:
      "A canal ring built in the 1600s and still the best way to orient yourself. Cycling is the default, and hotel rooms are famously narrow.",
    avgStayCost: 155,
    avgMealCost: 48,
  },
  {
    slug: "prague",
    name: "Prague",
    country: "Czechia",
    countryCode: "CZ",
    region: "Europe",
    lat: 50.0755,
    lng: 14.4378,
    costIndex: 45,
    popularity: 84,
    currency: "CZK",
    timezone: "Europe/Prague",
    description:
      "Gothic spires that survived both world wars largely intact, above a river valley you can cross on foot. The cheapest of the classic European capitals.",
    avgStayCost: 78,
    avgMealCost: 26,
  },
  {
    slug: "lisbon",
    name: "Lisbon",
    country: "Portugal",
    countryCode: "PT",
    region: "Europe",
    lat: 38.7223,
    lng: -9.1393,
    costIndex: 52,
    popularity: 87,
    currency: "EUR",
    timezone: "Europe/Lisbon",
    description:
      "Seven hills of tiled facades running down to the Tagus, with trams doing the climbing for you. Atlantic light makes it the brightest capital in Europe.",
    avgStayCost: 92,
    avgMealCost: 30,
  },
  {
    slug: "istanbul",
    name: "Istanbul",
    country: "Türkiye",
    countryCode: "TR",
    region: "Europe",
    lat: 41.0082,
    lng: 28.9784,
    costIndex: 38,
    popularity: 90,
    currency: "TRY",
    timezone: "Europe/Istanbul",
    description:
      "The only city on two continents, with a ferry commute across the Bosphorus that doubles as the best sightseeing in town. Byzantine and Ottoman layers sit side by side.",
    avgStayCost: 62,
    avgMealCost: 22,
  },
  {
    slug: "vienna",
    name: "Vienna",
    country: "Austria",
    countryCode: "AT",
    region: "Europe",
    lat: 48.2082,
    lng: 16.3738,
    costIndex: 70,
    popularity: 80,
    currency: "EUR",
    timezone: "Europe/Vienna",
    description:
      "Imperial architecture, an opera house with standing tickets for a few euros, and coffee houses that expect you to stay for hours. Consistently ranked the most liveable city in the world.",
    avgStayCost: 135,
    avgMealCost: 44,
  },

  /* ------------------------------------------------------------------ Asia */
  {
    slug: "tokyo",
    name: "Tokyo",
    country: "Japan",
    countryCode: "JP",
    region: "Asia",
    lat: 35.6762,
    lng: 139.6503,
    costIndex: 72,
    popularity: 97,
    currency: "JPY",
    timezone: "Asia/Tokyo",
    description:
      "Twenty-three wards that each feel like their own city, tied together by the most reliable rail network on earth. Eating well here costs less than you'd expect.",
    avgStayCost: 140,
    avgMealCost: 40,
  },
  {
    slug: "kyoto",
    name: "Kyoto",
    country: "Japan",
    countryCode: "JP",
    region: "Asia",
    lat: 35.0116,
    lng: 135.7681,
    costIndex: 66,
    popularity: 94,
    currency: "JPY",
    timezone: "Asia/Tokyo",
    description:
      "Sixteen hundred temples and a preserved grid of machiya townhouses, walkable in a way Tokyo isn't. Cherry blossom and autumn colour both draw crowds worth planning around.",
    avgStayCost: 125,
    avgMealCost: 38,
  },
  {
    slug: "osaka",
    name: "Osaka",
    country: "Japan",
    countryCode: "JP",
    region: "Asia",
    lat: 34.6937,
    lng: 135.5023,
    costIndex: 60,
    popularity: 86,
    currency: "JPY",
    timezone: "Asia/Tokyo",
    description:
      "Japan's kitchen, louder and more casual than Kyoto an hour up the line. Street food after dark is the whole point.",
    avgStayCost: 105,
    avgMealCost: 34,
  },
  {
    slug: "seoul",
    name: "Seoul",
    country: "South Korea",
    countryCode: "KR",
    region: "Asia",
    lat: 37.5665,
    lng: 126.978,
    costIndex: 62,
    popularity: 89,
    currency: "KRW",
    timezone: "Asia/Seoul",
    description:
      "Palaces and mountain trails inside a city of ten million, with neighbourhoods that turn over every few years. Public transport runs late and costs almost nothing.",
    avgStayCost: 110,
    avgMealCost: 32,
  },
  {
    slug: "bangkok",
    name: "Bangkok",
    country: "Thailand",
    countryCode: "TH",
    region: "Asia",
    lat: 13.7563,
    lng: 100.5018,
    costIndex: 34,
    popularity: 92,
    currency: "THB",
    timezone: "Asia/Bangkok",
    description:
      "Gilded temples, canal boats and a street food scene that's genuinely world class. The heat means most people plan around a mid-afternoon break.",
    avgStayCost: 55,
    avgMealCost: 16,
  },
  {
    slug: "singapore",
    name: "Singapore",
    country: "Singapore",
    countryCode: "SG",
    region: "Asia",
    lat: 1.3521,
    lng: 103.8198,
    costIndex: 82,
    popularity: 85,
    currency: "SGD",
    timezone: "Asia/Singapore",
    description:
      "A city-state you can cross in forty minutes, with hawker centres serving Michelin-listed food for a few dollars. Accommodation is the expensive part.",
    avgStayCost: 170,
    avgMealCost: 30,
  },
  {
    slug: "ubud",
    name: "Ubud",
    country: "Indonesia",
    countryCode: "ID",
    region: "Asia",
    lat: -8.5069,
    lng: 115.2625,
    costIndex: 30,
    popularity: 83,
    currency: "IDR",
    timezone: "Asia/Makassar",
    description:
      "Bali's inland cultural centre, ringed by terraced rice fields and river gorges. Quieter and greener than the island's southern beach towns.",
    avgStayCost: 48,
    avgMealCost: 15,
  },
  {
    slug: "dubai",
    name: "Dubai",
    country: "United Arab Emirates",
    countryCode: "AE",
    region: "Asia",
    lat: 25.2048,
    lng: 55.2708,
    costIndex: 80,
    popularity: 88,
    currency: "AED",
    timezone: "Asia/Dubai",
    description:
      "A skyline built in thirty years, with desert an hour from the tallest building on earth. Everything is air-conditioned, which matters from May to September.",
    avgStayCost: 160,
    avgMealCost: 50,
  },

  /* ------------------------------------------------------------ South Asia */
  {
    slug: "goa",
    name: "Goa",
    country: "India",
    countryCode: "IN",
    region: "South Asia",
    lat: 15.4909,
    lng: 73.8278,
    costIndex: 28,
    popularity: 88,
    currency: "INR",
    timezone: "Asia/Kolkata",
    description:
      "A hundred kilometres of coastline with Portuguese churches inland and very different beaches north and south. Peak season runs November to February.",
    avgStayCost: 42,
    avgMealCost: 13,
  },
  {
    slug: "jaipur",
    name: "Jaipur",
    country: "India",
    countryCode: "IN",
    region: "South Asia",
    lat: 26.9124,
    lng: 75.7873,
    costIndex: 24,
    popularity: 85,
    currency: "INR",
    timezone: "Asia/Kolkata",
    description:
      "A planned city from 1727, painted pink for a royal visit and never repainted. Forts on the ridgeline above give the best sense of its scale.",
    avgStayCost: 38,
    avgMealCost: 11,
  },
  {
    slug: "udaipur",
    name: "Udaipur",
    country: "India",
    countryCode: "IN",
    region: "South Asia",
    lat: 24.5854,
    lng: 73.7125,
    costIndex: 26,
    popularity: 81,
    currency: "INR",
    timezone: "Asia/Kolkata",
    description:
      "Palaces built out over a chain of artificial lakes, with the Aravalli hills behind. Small enough to cover on foot in two days.",
    avgStayCost: 45,
    avgMealCost: 12,
  },
  {
    slug: "kochi",
    name: "Kochi",
    country: "India",
    countryCode: "IN",
    region: "South Asia",
    lat: 9.9312,
    lng: 76.2673,
    costIndex: 25,
    popularity: 74,
    currency: "INR",
    timezone: "Asia/Kolkata",
    description:
      "A spice port that Portuguese, Dutch and British traders each rebuilt in turn. The backwaters start an hour south.",
    avgStayCost: 40,
    avgMealCost: 11,
  },
  {
    slug: "varanasi",
    name: "Varanasi",
    country: "India",
    countryCode: "IN",
    region: "South Asia",
    lat: 25.3176,
    lng: 82.9739,
    costIndex: 20,
    popularity: 78,
    currency: "INR",
    timezone: "Asia/Kolkata",
    description:
      "One of the oldest continuously inhabited cities anywhere, built along eighty riverfront ghats. Dawn on the Ganges is the reason most people come.",
    avgStayCost: 30,
    avgMealCost: 9,
  },
  {
    slug: "leh",
    name: "Leh",
    country: "India",
    countryCode: "IN",
    region: "South Asia",
    lat: 34.1526,
    lng: 77.5771,
    costIndex: 32,
    popularity: 72,
    currency: "INR",
    timezone: "Asia/Kolkata",
    description:
      "A high-desert town at 3,500 m, surrounded by Buddhist monasteries and road passes that only open in summer. Budget two days to acclimatise before doing anything strenuous.",
    avgStayCost: 44,
    avgMealCost: 13,
  },
  {
    slug: "rishikesh",
    name: "Rishikesh",
    country: "India",
    countryCode: "IN",
    region: "South Asia",
    lat: 30.0869,
    lng: 78.2676,
    costIndex: 22,
    popularity: 76,
    currency: "INR",
    timezone: "Asia/Kolkata",
    description:
      "Where the Ganges leaves the Himalaya, with ashrams on one bank and whitewater rafting on the other. Alcohol-free by law, which sets the tone.",
    avgStayCost: 32,
    avgMealCost: 9,
  },
  {
    slug: "mumbai",
    name: "Mumbai",
    country: "India",
    countryCode: "IN",
    region: "South Asia",
    lat: 19.076,
    lng: 72.8777,
    costIndex: 36,
    popularity: 84,
    currency: "INR",
    timezone: "Asia/Kolkata",
    description:
      "Art Deco seafront, Victorian railway terminals and the densest street life in the country. Avoid the monsoon months of June and July.",
    avgStayCost: 62,
    avgMealCost: 16,
  },

  /* -------------------------------------------------------------- Americas */
  {
    slug: "new-york",
    name: "New York",
    country: "United States",
    countryCode: "US",
    region: "Americas",
    lat: 40.7128,
    lng: -74.006,
    costIndex: 92,
    popularity: 96,
    currency: "USD",
    timezone: "America/New_York",
    description:
      "Dense enough that a day here covers more ground than a week elsewhere, and the subway runs all night. Hotel prices swing wildly by season.",
    avgStayCost: 240,
    avgMealCost: 70,
  },
  {
    slug: "san-francisco",
    name: "San Francisco",
    country: "United States",
    countryCode: "US",
    region: "Americas",
    lat: 37.7749,
    lng: -122.4194,
    costIndex: 90,
    popularity: 82,
    currency: "USD",
    timezone: "America/Los_Angeles",
    description:
      "Seven square miles of hills, fog and Victorian terraces, with redwoods and wine country within two hours. Summer is the coldest season, genuinely.",
    avgStayCost: 215,
    avgMealCost: 62,
  },
  {
    slug: "mexico-city",
    name: "Mexico City",
    country: "Mexico",
    countryCode: "MX",
    region: "Americas",
    lat: 19.4326,
    lng: -99.1332,
    costIndex: 40,
    popularity: 86,
    currency: "MXN",
    timezone: "America/Mexico_City",
    description:
      "An Aztec capital, a colonial one and a modernist one occupying the same ground. The altitude of 2,240 m catches most visitors out on day one.",
    avgStayCost: 70,
    avgMealCost: 22,
  },
  {
    slug: "cancun",
    name: "Cancún",
    country: "Mexico",
    countryCode: "MX",
    region: "Americas",
    lat: 21.1619,
    lng: -86.8515,
    costIndex: 55,
    popularity: 80,
    currency: "MXN",
    timezone: "America/Cancun",
    description:
      "Caribbean reef and white sand with Maya ruins an easy drive inland. Hurricane season peaks in September.",
    avgStayCost: 118,
    avgMealCost: 35,
  },
  {
    slug: "rio-de-janeiro",
    name: "Rio de Janeiro",
    country: "Brazil",
    countryCode: "BR",
    region: "Americas",
    lat: -22.9068,
    lng: -43.1729,
    costIndex: 42,
    popularity: 87,
    currency: "BRL",
    timezone: "America/Sao_Paulo",
    description:
      "Granite peaks dropping straight into the Atlantic, with rainforest inside the city limits. Beach neighbourhoods each have a distinct crowd.",
    avgStayCost: 76,
    avgMealCost: 24,
  },
  {
    slug: "buenos-aires",
    name: "Buenos Aires",
    country: "Argentina",
    countryCode: "AR",
    region: "Americas",
    lat: -34.6037,
    lng: -58.3816,
    costIndex: 33,
    popularity: 79,
    currency: "ARS",
    timezone: "America/Argentina/Buenos_Aires",
    description:
      "European boulevards and Italian food in South America, with a bookshop-per-capita record. Dinner at ten is normal, not late.",
    avgStayCost: 58,
    avgMealCost: 20,
  },
  {
    slug: "cusco",
    name: "Cusco",
    country: "Peru",
    countryCode: "PE",
    region: "Americas",
    lat: -13.5319,
    lng: -71.9675,
    costIndex: 30,
    popularity: 83,
    currency: "PEN",
    timezone: "America/Lima",
    description:
      "The Inca capital, with Spanish churches built directly on Inca foundations you can still see. It sits at 3,400 m and is the base for Machu Picchu.",
    avgStayCost: 52,
    avgMealCost: 17,
  },
  {
    slug: "vancouver",
    name: "Vancouver",
    country: "Canada",
    countryCode: "CA",
    region: "Americas",
    lat: 49.2827,
    lng: -123.1207,
    costIndex: 74,
    popularity: 77,
    currency: "CAD",
    timezone: "America/Vancouver",
    description:
      "Ocean on one side, coastal mountains on the other, and a rainforest park bigger than the downtown core. It rains for much of the winter.",
    avgStayCost: 148,
    avgMealCost: 45,
  },

  /* -------------------------------------------------- Africa & Middle East */
  {
    slug: "cape-town",
    name: "Cape Town",
    country: "South Africa",
    countryCode: "ZA",
    region: "Africa & Middle East",
    lat: -33.9249,
    lng: 18.4241,
    costIndex: 38,
    popularity: 86,
    currency: "ZAR",
    timezone: "Africa/Johannesburg",
    description:
      "A flat-topped mountain in the middle of a city, with penguins and vineyards within an hour. Seasons are inverted, so December is high summer.",
    avgStayCost: 72,
    avgMealCost: 24,
  },
  {
    slug: "marrakech",
    name: "Marrakech",
    country: "Morocco",
    countryCode: "MA",
    region: "Africa & Middle East",
    lat: 31.6295,
    lng: -7.9811,
    costIndex: 32,
    popularity: 82,
    currency: "MAD",
    timezone: "Africa/Casablanca",
    description:
      "A walled medina you will get lost in, with the Atlas mountains visible on clear days. Riads hide large courtyards behind blank street walls.",
    avgStayCost: 58,
    avgMealCost: 18,
  },
  {
    slug: "cairo",
    name: "Cairo",
    country: "Egypt",
    countryCode: "EG",
    region: "Africa & Middle East",
    lat: 30.0444,
    lng: 31.2357,
    costIndex: 26,
    popularity: 84,
    currency: "EGP",
    timezone: "Africa/Cairo",
    description:
      "The pyramids sit at the edge of a city of twenty million, closer than most photographs suggest. Islamic Cairo has a thousand years of architecture in walking distance.",
    avgStayCost: 45,
    avgMealCost: 13,
  },
  {
    slug: "zanzibar",
    name: "Zanzibar",
    country: "Tanzania",
    countryCode: "TZ",
    region: "Africa & Middle East",
    lat: -6.1659,
    lng: 39.2026,
    costIndex: 34,
    popularity: 75,
    currency: "TZS",
    timezone: "Africa/Dar_es_Salaam",
    description:
      "A Swahili trading town of coral-stone alleys, with reef beaches an hour away on the east coast. The two rainy seasons are worth planning around.",
    avgStayCost: 66,
    avgMealCost: 19,
  },
  {
    slug: "nairobi",
    name: "Nairobi",
    country: "Kenya",
    countryCode: "KE",
    region: "Africa & Middle East",
    lat: -1.2921,
    lng: 36.8219,
    costIndex: 35,
    popularity: 70,
    currency: "KES",
    timezone: "Africa/Nairobi",
    description:
      "The only capital city with a national park on its doorstep, where lions share a horizon with the skyline. Most safari itineraries start here.",
    avgStayCost: 64,
    avgMealCost: 20,
  },
  {
    slug: "petra",
    name: "Petra",
    country: "Jordan",
    countryCode: "JO",
    region: "Africa & Middle East",
    lat: 30.3285,
    lng: 35.4444,
    costIndex: 48,
    popularity: 79,
    currency: "JOD",
    timezone: "Asia/Amman",
    description:
      "A Nabataean city carved into rose sandstone, reached through a kilometre-long slot canyon. Two days lets you walk the high routes as well as the main street.",
    avgStayCost: 88,
    avgMealCost: 26,
  },
  {
    slug: "doha",
    name: "Doha",
    country: "Qatar",
    countryCode: "QA",
    region: "Africa & Middle East",
    lat: 25.2854,
    lng: 51.531,
    costIndex: 72,
    popularity: 68,
    currency: "QAR",
    timezone: "Asia/Qatar",
    description:
      "A corniche of new towers facing a rebuilt souq, with serious museums funding the difference. Winter is the only comfortable season outdoors.",
    avgStayCost: 145,
    avgMealCost: 42,
  },
  {
    slug: "muscat",
    name: "Muscat",
    country: "Oman",
    countryCode: "OM",
    region: "Africa & Middle East",
    lat: 23.588,
    lng: 58.3829,
    costIndex: 58,
    popularity: 66,
    currency: "OMR",
    timezone: "Asia/Muscat",
    description:
      "Low white buildings between bare mountains and the Gulf of Oman, with a strict height limit that keeps the skyline flat. Wadis and forts are a short drive inland.",
    avgStayCost: 110,
    avgMealCost: 32,
  },

  /* --------------------------------------------------------------- Oceania */
  {
    slug: "sydney",
    name: "Sydney",
    country: "Australia",
    countryCode: "AU",
    region: "Oceania",
    lat: -33.8688,
    lng: 151.2093,
    costIndex: 78,
    popularity: 91,
    currency: "AUD",
    timezone: "Australia/Sydney",
    description:
      "A drowned river valley turned harbour city, with more than a hundred beaches inside the metro area. Ferries are public transport and the best view in town.",
    avgStayCost: 160,
    avgMealCost: 48,
  },
  {
    slug: "melbourne",
    name: "Melbourne",
    country: "Australia",
    countryCode: "AU",
    region: "Oceania",
    lat: -37.8136,
    lng: 144.9631,
    costIndex: 72,
    popularity: 84,
    currency: "AUD",
    timezone: "Australia/Melbourne",
    description:
      "Laneways of coffee and street art on a Victorian grid, with a free tram zone covering the centre. Four seasons in one day is a local saying, not a joke.",
    avgStayCost: 138,
    avgMealCost: 44,
  },
  {
    slug: "queenstown",
    name: "Queenstown",
    country: "New Zealand",
    countryCode: "NZ",
    region: "Oceania",
    lat: -45.0312,
    lng: 168.6626,
    costIndex: 68,
    popularity: 81,
    currency: "NZD",
    timezone: "Pacific/Auckland",
    description:
      "A lakeside town under the Remarkables range that invented commercial bungy jumping. Skiing in winter, hiking and paragliding the rest of the year.",
    avgStayCost: 130,
    avgMealCost: 42,
  },
  {
    slug: "auckland",
    name: "Auckland",
    country: "New Zealand",
    countryCode: "NZ",
    region: "Oceania",
    lat: -36.8485,
    lng: 174.7633,
    costIndex: 65,
    popularity: 73,
    currency: "NZD",
    timezone: "Pacific/Auckland",
    description:
      "Built across fifty dormant volcanic cones between two harbours, with islands a ferry ride offshore. Most South Island trips start with a connection here.",
    avgStayCost: 118,
    avgMealCost: 38,
  },
  {
    slug: "gold-coast",
    name: "Gold Coast",
    country: "Australia",
    countryCode: "AU",
    region: "Oceania",
    lat: -28.0167,
    lng: 153.4,
    costIndex: 62,
    popularity: 72,
    currency: "AUD",
    timezone: "Australia/Brisbane",
    description:
      "Fifty-seven kilometres of surf beach backed by high-rises, with subtropical rainforest twenty minutes inland. The hinterland is the half most visitors miss.",
    avgStayCost: 112,
    avgMealCost: 36,
  },
  {
    slug: "perth",
    name: "Perth",
    country: "Australia",
    countryCode: "AU",
    region: "Oceania",
    lat: -31.9505,
    lng: 115.8605,
    costIndex: 66,
    popularity: 64,
    currency: "AUD",
    timezone: "Australia/Perth",
    description:
      "One of the most isolated cities on earth, with a riverside park larger than Central Park. Quokkas on Rottnest Island are a twenty-five minute ferry away.",
    avgStayCost: 120,
    avgMealCost: 38,
  },
  {
    slug: "hobart",
    name: "Hobart",
    country: "Australia",
    countryCode: "AU",
    region: "Oceania",
    lat: -42.8821,
    lng: 147.3272,
    costIndex: 60,
    popularity: 62,
    currency: "AUD",
    timezone: "Australia/Hobart",
    description:
      "A Georgian port under Mount Wellington, with Antarctic research ships in the docks. Tasmania's wilderness starts about an hour out of town.",
    avgStayCost: 105,
    avgMealCost: 36,
  },
  {
    slug: "nadi",
    name: "Nadi",
    country: "Fiji",
    countryCode: "FJ",
    region: "Oceania",
    lat: -17.7765,
    lng: 177.4356,
    costIndex: 50,
    popularity: 68,
    currency: "FJD",
    timezone: "Pacific/Fiji",
    description:
      "The arrival point for Fiji and the jumping-off port for the Mamanuca and Yasawa islands. Most people use it as a hinge rather than a destination.",
    avgStayCost: 95,
    avgMealCost: 28,
  },
];
